"""empty message

Revision ID: 8633af786465
Revises: 8de81acf5dab
Create Date: 2024-10-23 14:48:55.480538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8633af786465'
down_revision = '8de81acf5dab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('birth_year', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('eye_color', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('films', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('gender', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('hair_color', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('height', sa.Float(precision=10), nullable=True))
        batch_op.add_column(sa.Column('homeworld', sa.String(length=50), nullable=True))
        batch_op.drop_column('population')
        batch_op.drop_column('orbital_period')
        batch_op.drop_column('climate')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('climate', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('orbital_period', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('population', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('homeworld')
        batch_op.drop_column('height')
        batch_op.drop_column('hair_color')
        batch_op.drop_column('gender')
        batch_op.drop_column('films')
        batch_op.drop_column('eye_color')
        batch_op.drop_column('birth_year')

    # ### end Alembic commands ###
